### ISSUE TITLE
What kind of i2c driver are you using to read the sensor?

### ISSUE THREAD

**Issue by dcomins** [lucaong/nerves_thermal_camera#1]
I saw many libraries that uses bcm2835_i2c in order to read the data sensor, do yo use the same i2c driver o the generic Linux i2c driver? Could it be easy to obtain the temp values from a python script with your library?

**Comment by lucaong** [comment]
this project is a high-level implementation on Nerves that uses [this other lower level library](https://github.com/lucaong/elixir_mlx90640) I created.

The lower level library is designed to read the temperature values in a stream from the Elixir language. The C driver uses modified versions of the Melexis device library and port for the generic Linux I2C driver provided by Pimoroni (you can see the C++ files here: https://github.com/lucaong/elixir_mlx90640/tree/master/src).

This project and its low level library is designed to be used with the Elixir language. That said, the C files could in theory be used on Linux from other languages, provided that:

  - The I2C driver is installed on the system (e.g. libi2c-dev on Debian).
  - The files are compiled for the target architecture
  - The script (e.g. Python) takes care of decoding the binary protocol that my `main.cpp` implements (you can read some details about it in the comment here: https://github.com/lucaong/elixir_mlx90640/blob/master/src/main.cpp#L41)

I assume that it would be just easier to use the Pimoroni C library though, maybe modifying it for your purposes :)

Let me know if you need some information about it, I am not a Python expert but I got to learn a few things about the MLX device library making this project.

**Comment by dcomins** [comment]
Hello Luca,

Thanks for the fast answer! First of all I would like to create a executable main from your (main.cpp) https://github.com/lucaong/elixir_mlx90640/blob/master/src/main.cpp in order to know if I can read the data from my MLX90640 using generic Linux I2C driver. In Pimoroni's driver I only could read my MLX90640 data if I use the bcm2835 i2c driver and I would like to avoid it, when I choseed to use generic Linux I2C driver I got many errors and I could not read the temperature matrix.

ould you post here the commands in order to compile and obtain the executable main from main.cpp, I am not sure if I have to put "g++ -I. -std=c++11 -std=c++11 -c -o main.o main.cpp" and "g++ -L main.o -o main" I do not know what are the correct commands.

After that my idea is to create a .so file from a custom main where I create custom functions and I can access with python to the cpp functions with the library ctypes and extern "C".

I really appreciate your help,

Regards,

Diego Comin

**Comment by lucaong** [comment]
The library (cross-)compiles the C++ files upon installation using [this Makefile](https://github.com/lucaong/elixir_mlx90640/blob/master/Makefile). Nerves uses buildroot to cross-compile the executables on the target system, but even if you don't need cross-compilation, the Makefile should still be able to compile the library, provided that you have the generic I2C driver installed.

If you compile my library using the Makefile, you will obtain an executable program (and the `.o` and `.so` files). When started, the program will keep outputting to the STDOUT the measurements for each frame using a custom binary protocol. Optionally, you can set the number of frames per second as the first command-line argument (e.g. `priv/mlx90640 4` for 4 frames per second).

The binary protocol is rather simple: each frame consist in a 2-byte header indicating the data length in bytes, then the data itself, in which each pixel is a temperature value represented as 2 bytes, with the meaning indicated here: https://github.com/lucaong/elixir_mlx90640/blob/master/src/main.cpp#L41https://github.com/lucaong/elixir_mlx90640/blob/master/src/main.cpp#L41

I hope this helps. Let me know if you need more information.

Best,
Luca

**Comment by dcomins** [comment]
Hello Luca,

As you said I compiled your files and I obtained an executable file in priv/mlx90640. I put the command ./mlx90640 4 and I am not able to read the sensor, I attached the I2C Read error below:

![image](https://user-images.githubusercontent.com/20353282/51312251-1fce6480-1a4b-11e9-8051-aa6feef170c7.png)

Of course I am able to detect the address of the MLX90640 sensor with the command "i2cdetect -y 1":

![image](https://user-images.githubusercontent.com/20353282/51312271-2bba2680-1a4b-11e9-98d5-b90a5b601c0f.png)

What could be the source of the error? I am using a Raspberry pi Zero with the SDA and SCL lines connected in these pins:

![image](https://user-images.githubusercontent.com/20353282/51312154-ee559900-1a4a-11e9-915e-be0a5598d9f7.png)

Regards,

Diego Comín

**Comment by lucaong** [comment]
Hi Diego,
the setup looks good to me, and the device is detected on the correct I2C address. I am not sure what could cause the error: the same setup works for me on Raspbian. The error occurs in the `MLX90640_I2CRead` function, but I have no specific insight on why. I would do the following:

  1. Double-check all the physical connections. I know they're probably already fine, but better to make really sure.
  2. Set the I2C baudrate explicitly to the same value I use in Nerves. I remember I had to tweak it to get reliable communication. In my Nerves firmware, I set this in the `/boot/config.txt`:

```
dtparam=i2c_arm=on,i2c_arm_baudrate=400000
```

I hope this helps,
Luca

**Comment by dcomins** [comment]
DId you install some generic I2C driver in Raspbian (eg: sudo apt-get install libi2c-dev) to get it working?

**Comment by lucaong** [comment]
Yes, correct.
The Nerves firmware already includes it, but on Raspbian (or other Debian) you need to install `libi2c-dev` (the generic Linux I2C driver) in order for it to work, as written in the README of the `elixir_mlx90640` library.

**Comment by dcomins** [comment]
Ok, I detected the problem. My issue is that if I install the bcm2835 i2c library and I use generic I2C Linux driver, the last one gets bugged. I changed my RP I only used generic I2C Linux driver and I was able to detect the temp data. Then, I installed the bcm2835 library I continued on using your executable and I get I2C Read Error.

Do you know any way to unistall the bcm2835 i2c driver I installed from?: https://github.com/pimoroni/mlx90640-library

**Comment by lucaong** [comment]
Hi Diego,
great that you have found the reason. I do not know how to uninstall the `bcm2835` driver, but I would suggest to first try to `cd` to the `bcm2835` folder and run `sudo make uninstall`.

**Comment by dcomins** [comment]
Hi Luca,

My final question, is it possible to read the sensor at an i2c speed of 10kHz?? 
I mean dtparam=i2c_arm=on,i2c_arm_baudrate=10000

**Comment by lucaong** [comment]
Hi Diego,
the datasheet for the MLX90640 mandates a maximum baud rate of 400KHz when reading from the EEPROM, and 1MHz otherwise. Lower baud rates will be fine, but you might not be able to increase the frame rates then. 10KHz seem quite slow though, so you should check if it still works. It probably will, but the MLX90640 is known for being a very time sensitive sensor, and I never tried myself at that frequency.
