### ISSUE TITLE
Help !! could not compile dependency :elixir_mlx90640, "mix compile" failed

### ISSUE THREAD

**Issue by JatinJani** [lucaong/nerves_thermal_camera#20]
Hello, Please can you guide / assist. Following the guide / instructions letter by letter and having taken care of all the errors in between here is the last thing that happens when I run : make firmware 
###########
==> elixir_mlx90640
/Users/Jatin/.nerves/artifacts/nerves_toolchain_armv6_nerves_linux_gnueabihf-darwin_x86_64-1.6.1/bin/armv6-nerves-linux-gnueabihf-g++ -mabi=aapcs-linux -mfpu=vfp -marm -fstack-protector-strong -mfloat-abi=hard -mcpu=arm1176jzf-s -fPIE -pie -Wl,-z,now -Wl,-z,relro -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -pipe -O2 --sysroot /Users/Jatin/.nerves/artifacts/nerves_system_rpi0-portable-1.21.1/staging -I. -std=c++11 -fPIC -I. -shared -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 --sysroot /Users/Jatin/.nerves/artifacts/nerves_system_rpi0-portable-1.21.1/staging arm -c -o src/MLX90640_LINUX_I2C_Driver.o src/MLX90640_LINUX_I2C_Driver.cpp
armv6-nerves-linux-gnueabihf-g++: warning: arm: linker input file unused because linking not done
armv6-nerves-linux-gnueabihf-g++: error: arm: linker input file not found: No such file or directory
make[1]: *** [src/MLX90640_LINUX_I2C_Driver.o] Error 1
could not compile dependency :elixir_mlx90640, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile elixir_mlx90640", update it with "mix deps.update elixir_mlx90640" or clean it with "mix deps.clean elixir_mlx90640"
==> firmware
** (Mix) Could not compile with "make" (exit status: 2).
You need to have gcc and make installed. Try running the
commands "gcc --version" and / or "make --version". If these programs
are not installed, you will be prompted to install them.

make: *** [firmware] Error 1

###########

Running the environment on : Macbook Pro - Big Sur 11.7.2

Much appreciated.
Thanks.

**Comment by ondrejbartas** [comment]
Hi I am having same problem on Mac Book Pro M1

**Comment by lucaong** [comment]
Hi @JatinJani and @ondrejbartas , thanks for reporting this issue. It should be now fixed, it was a problem with the `Makefile` in the dependency [`elixir_mlx90640`](https://github.com/lucaong/elixir_mlx90640).

Can you confirm it works now?
